apiVersion: v1
kind: Service
metadata:
  name: hello-world-service
  namespace: hello-world
  labels:
    app: hello-world
spec:
  selector:
    app: hello-world
  ports:
  - protocol: TCP
    port: 8080
    nodePort: 30001
  type: NodePort